### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/sample-crowdsale-starter/migrations'

### ISSUE THREAD

**Issue by trademindx** [OpenZeppelin/sample-crowdsale-starter#1]
This is really a great starter project. However running:

```
npm install
npm test
```

results in an error because migrations directory does not exist in the project.

Happy to do a fix and a pull request if that is acceptable.

**Comment by debianmaster** [comment]
@trademindx   can you please add migrations ?

**Comment by trademindx** [comment]
It's been added by @spalladino who owns the repo: https://github.com/OpenZeppelin/sample-crowdsale-starter/commit/639ab85e1a20997bab786b30764034744e3177f1

Just do a pull to pickup those changes.
